development:
  adapter: postgresql
  encoding: unicode
  database: archimap_development
  pool: 5
  username: gavincassidy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: archimap_test
  pool: 5
  username: gavincassidy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: archimap_production
  pool: 5
  username: gavincassidy
  password: